import { db } from "@/lib/prisma";

// ─── Role Names ──────────────────────────────────────────────────

export const ROLES = {
  OWNER: "OWNER",
  ADMIN: "ADMIN",
  DIRECTOR: "DIRECTOR",
  TEACHER: "TEACHER",
  TRAINER: "TRAINER",
  ACCOUNTANT: "ACCOUNTANT",
  RECEPTIONIST: "RECEPTIONIST",
  PARENT: "PARENT",
  STUDENT: "STUDENT",
} as const;

export type RoleName = (typeof ROLES)[keyof typeof ROLES];

// ─── Permission Keys ─────────────────────────────────────────────

export const PERMISSIONS = {
  // Students
  STUDENTS_READ: "STUDENTS_READ",
  STUDENTS_CREATE: "STUDENTS_CREATE",
  STUDENTS_UPDATE: "STUDENTS_UPDATE",
  STUDENTS_DELETE: "STUDENTS_DELETE",
  // Teachers
  TEACHERS_READ: "TEACHERS_READ",
  TEACHERS_CREATE: "TEACHERS_CREATE",
  TEACHERS_UPDATE: "TEACHERS_UPDATE",
  TEACHERS_DELETE: "TEACHERS_DELETE",
  // Finance
  FINANCE_READ: "FINANCE_READ",
  FINANCE_MANAGE: "FINANCE_MANAGE",
  // Attendance
  ATTENDANCE_READ: "ATTENDANCE_READ",
  ATTENDANCE_MANAGE: "ATTENDANCE_MANAGE",
  // Organization
  ORG_SETTINGS: "ORG_SETTINGS",
  ORG_MEMBERS: "ORG_MEMBERS",
  ORG_BILLING: "ORG_BILLING",
  // Branches
  BRANCHES_READ: "BRANCHES_READ",
  BRANCHES_MANAGE: "BRANCHES_MANAGE",
  // Reports
  REPORTS_READ: "REPORTS_READ",
  REPORTS_CREATE: "REPORTS_CREATE",
  // Roles
  ROLES_MANAGE: "ROLES_MANAGE",
  // Rooms & Scheduling
  ROOMS_READ: "ROOMS_READ",
  ROOMS_MANAGE: "ROOMS_MANAGE",
  SCHEDULES_READ: "SCHEDULES_READ",
  SCHEDULES_MANAGE: "SCHEDULES_MANAGE",
  // Academic Tracking
  GRADES_READ: "GRADES_READ",
  GRADES_MANAGE: "GRADES_MANAGE",
  // Finance
  INVOICES_READ: "INVOICES_READ",
  INVOICES_MANAGE: "INVOICES_MANAGE",
  PAYMENTS_READ: "PAYMENTS_READ",
  PAYMENTS_MANAGE: "PAYMENTS_MANAGE",
  // Notifications & Automation
  NOTIFICATIONS_READ: "NOTIFICATIONS_READ",
  NOTIFICATIONS_MANAGE: "NOTIFICATIONS_MANAGE",
  AUTOMATIONS_READ: "AUTOMATIONS_READ",
  AUTOMATIONS_MANAGE: "AUTOMATIONS_MANAGE",
  // AI
  AI_READ: "AI_READ",
  AI_USE: "AI_USE",
  AI_MANAGE: "AI_MANAGE",
  // Admissions
  ADMISSIONS_READ: "ADMISSIONS_READ",
  ADMISSIONS_MANAGE: "ADMISSIONS_MANAGE",
  // Homework
  HOMEWORK_READ: "HOMEWORK_READ",
  HOMEWORK_MANAGE: "HOMEWORK_MANAGE",
  // Report Cards
  REPORT_CARDS_READ: "REPORT_CARDS_READ",
  REPORT_CARDS_MANAGE: "REPORT_CARDS_MANAGE",
  // Announcements
  ANNOUNCEMENTS_READ: "ANNOUNCEMENTS_READ",
  ANNOUNCEMENTS_MANAGE: "ANNOUNCEMENTS_MANAGE",
  // Documents
  DOCUMENTS_READ: "DOCUMENTS_READ",
  DOCUMENTS_MANAGE: "DOCUMENTS_MANAGE",
  // Leads / CRM
  LEADS_READ: "LEADS_READ",
  LEADS_MANAGE: "LEADS_MANAGE",
  // Trial Sessions
  TRIALS_READ: "TRIALS_READ",
  TRIALS_MANAGE: "TRIALS_MANAGE",
  // Teacher Availability
  AVAILABILITY_READ: "AVAILABILITY_READ",
  AVAILABILITY_MANAGE: "AVAILABILITY_MANAGE",
  // Teacher Compensation
  COMPENSATION_READ: "COMPENSATION_READ",
  COMPENSATION_MANAGE: "COMPENSATION_MANAGE",
  // Student Progress
  PROGRESS_READ: "PROGRESS_READ",
  PROGRESS_MANAGE: "PROGRESS_MANAGE",
  // Training Programs
  PROGRAMS_READ: "PROGRAMS_READ",
  PROGRAMS_MANAGE: "PROGRAMS_MANAGE",
  // Courses / Modules
  COURSES_READ: "COURSES_READ",
  COURSES_MANAGE: "COURSES_MANAGE",
  // Cohorts
  COHORTS_READ: "COHORTS_READ",
  COHORTS_MANAGE: "COHORTS_MANAGE",
  // Corporate Clients
  CORPORATE_READ: "CORPORATE_READ",
  CORPORATE_MANAGE: "CORPORATE_MANAGE",
  // Certificates
  CERTIFICATES_READ: "CERTIFICATES_READ",
  CERTIFICATES_MANAGE: "CERTIFICATES_MANAGE",
  // Competencies
  COMPETENCIES_READ: "COMPETENCIES_READ",
  COMPETENCIES_MANAGE: "COMPETENCIES_MANAGE",
  // Training Materials
  MATERIALS_READ: "MATERIALS_READ",
  MATERIALS_MANAGE: "MATERIALS_MANAGE",
  // Training Assignments
  TRAINING_ASSIGNMENTS_READ: "TRAINING_ASSIGNMENTS_READ",
  TRAINING_ASSIGNMENTS_MANAGE: "TRAINING_ASSIGNMENTS_MANAGE",
  // Proposals
  PROPOSALS_READ: "PROPOSALS_READ",
  PROPOSALS_MANAGE: "PROPOSALS_MANAGE",
  // Phase 5: Communication
  COMMUNICATION_READ: "COMMUNICATION_READ",
  COMMUNICATION_MANAGE: "COMMUNICATION_MANAGE",
  TEMPLATES_READ: "TEMPLATES_READ",
  TEMPLATES_MANAGE: "TEMPLATES_MANAGE",
  CAMPAIGNS_READ: "CAMPAIGNS_READ",
  CAMPAIGNS_MANAGE: "CAMPAIGNS_MANAGE",
  MESSAGES_READ: "MESSAGES_READ",
  MESSAGES_MANAGE: "MESSAGES_MANAGE",
  CONTACT_REQUESTS_READ: "CONTACT_REQUESTS_READ",
  CONTACT_REQUESTS_MANAGE: "CONTACT_REQUESTS_MANAGE",
  PROVIDERS_MANAGE: "PROVIDERS_MANAGE",
  DELIVERY_LOGS_READ: "DELIVERY_LOGS_READ",
  // Phase 6: AI Intelligence
  AI_ASSISTANT: "AI_ASSISTANT",
  AI_INSIGHTS_READ: "AI_INSIGHTS_READ",
  AI_READ_FINANCE: "AI_READ_FINANCE",
  AI_READ_STUDENTS: "AI_READ_STUDENTS",
  AI_READ_ATTENDANCE: "AI_READ_ATTENDANCE",
  AI_READ_ACADEMIC: "AI_READ_ACADEMIC",
  AI_READ_CRM: "AI_READ_CRM",
  AI_KNOWLEDGE_MANAGE: "AI_KNOWLEDGE_MANAGE",
  AI_RECOMMENDATIONS_READ: "AI_RECOMMENDATIONS_READ",
  AI_RECOMMENDATIONS_EXECUTE: "AI_RECOMMENDATIONS_EXECUTE",
  // Phase 7: SaaS Billing
  BILLING_READ: "BILLING_READ",
  BILLING_MANAGE: "BILLING_MANAGE",
  BILLING_SUBSCRIPTIONS: "BILLING_SUBSCRIPTIONS",
  BILLING_INVOICES: "BILLING_INVOICES",
  BILLING_PAYMENTS: "BILLING_PAYMENTS",
  BILLING_COUPONS: "BILLING_COUPONS",
  BILLING_PLATFORM: "BILLING_PLATFORM",
  BILLING_REFUNDS: "BILLING_REFUNDS",
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

// ─── Role-Permission Mappings ────────────────────────────────────

export const ROLE_PERMISSIONS: Record<RoleName, PermissionKey[]> = {
  OWNER: Object.values(PERMISSIONS),
  ADMIN: [
    "STUDENTS_READ", "STUDENTS_CREATE", "STUDENTS_UPDATE", "STUDENTS_DELETE",
    "TEACHERS_READ", "TEACHERS_CREATE", "TEACHERS_UPDATE", "TEACHERS_DELETE",
    "FINANCE_READ", "FINANCE_MANAGE",
    "ATTENDANCE_READ", "ATTENDANCE_MANAGE",
    "ORG_SETTINGS", "ORG_MEMBERS",
    "BRANCHES_READ", "BRANCHES_MANAGE",
    "REPORTS_READ", "REPORTS_CREATE",
    "ROLES_MANAGE",
    "ROOMS_READ", "ROOMS_MANAGE",
    "SCHEDULES_READ", "SCHEDULES_MANAGE",
    "GRADES_READ", "GRADES_MANAGE",
    "INVOICES_READ", "INVOICES_MANAGE",
    "PAYMENTS_READ", "PAYMENTS_MANAGE",
    "NOTIFICATIONS_READ", "NOTIFICATIONS_MANAGE",
    "AUTOMATIONS_READ", "AUTOMATIONS_MANAGE",
    "AI_READ", "AI_USE", "AI_MANAGE",
    "ADMISSIONS_READ", "ADMISSIONS_MANAGE",
    "HOMEWORK_READ", "HOMEWORK_MANAGE",
    "REPORT_CARDS_READ", "REPORT_CARDS_MANAGE",
    "ANNOUNCEMENTS_READ", "ANNOUNCEMENTS_MANAGE",
    "DOCUMENTS_READ", "DOCUMENTS_MANAGE",
    "LEADS_READ", "LEADS_MANAGE",
    "TRIALS_READ", "TRIALS_MANAGE",
    "AVAILABILITY_READ", "AVAILABILITY_MANAGE",
    "COMPENSATION_READ", "COMPENSATION_MANAGE",
    "PROGRESS_READ", "PROGRESS_MANAGE",
    "PROGRAMS_READ", "PROGRAMS_MANAGE",
    "COURSES_READ", "COURSES_MANAGE",
    "COHORTS_READ", "COHORTS_MANAGE",
    "CORPORATE_READ", "CORPORATE_MANAGE",
    "CERTIFICATES_READ", "CERTIFICATES_MANAGE",
    "COMPETENCIES_READ", "COMPETENCIES_MANAGE",
    "MATERIALS_READ", "MATERIALS_MANAGE",
    "TRAINING_ASSIGNMENTS_READ", "TRAINING_ASSIGNMENTS_MANAGE",
    "PROPOSALS_READ", "PROPOSALS_MANAGE",
    "COMMUNICATION_READ", "COMMUNICATION_MANAGE",
    "TEMPLATES_READ", "TEMPLATES_MANAGE",
    "CAMPAIGNS_READ", "CAMPAIGNS_MANAGE",
    "MESSAGES_READ", "MESSAGES_MANAGE",
    "CONTACT_REQUESTS_READ", "CONTACT_REQUESTS_MANAGE",
    "PROVIDERS_MANAGE",
    "DELIVERY_LOGS_READ",
    "AI_ASSISTANT", "AI_INSIGHTS_READ", "AI_READ_FINANCE", "AI_READ_STUDENTS",
    "AI_READ_ATTENDANCE", "AI_READ_ACADEMIC", "AI_READ_CRM",
    "AI_KNOWLEDGE_MANAGE", "AI_RECOMMENDATIONS_READ", "AI_RECOMMENDATIONS_EXECUTE",
    "BILLING_READ", "BILLING_MANAGE", "BILLING_SUBSCRIPTIONS", "BILLING_INVOICES",
    "BILLING_PAYMENTS", "BILLING_COUPONS", "BILLING_PLATFORM", "BILLING_REFUNDS",
  ],
  DIRECTOR: [
    "STUDENTS_READ", "STUDENTS_CREATE", "STUDENTS_UPDATE",
    "TEACHERS_READ", "TEACHERS_CREATE", "TEACHERS_UPDATE",
    "FINANCE_READ",
    "ATTENDANCE_READ", "ATTENDANCE_MANAGE",
    "BRANCHES_READ",
    "REPORTS_READ", "REPORTS_CREATE",
    "ROOMS_READ", "ROOMS_MANAGE",
    "SCHEDULES_READ", "SCHEDULES_MANAGE",
    "GRADES_READ", "GRADES_MANAGE",
    "INVOICES_READ", "INVOICES_MANAGE",
    "PAYMENTS_READ", "PAYMENTS_MANAGE",
    "NOTIFICATIONS_READ", "NOTIFICATIONS_MANAGE",
    "AUTOMATIONS_READ",
    "AI_READ", "AI_USE",
    "ADMISSIONS_READ", "ADMISSIONS_MANAGE",
    "HOMEWORK_READ", "HOMEWORK_MANAGE",
    "REPORT_CARDS_READ", "REPORT_CARDS_MANAGE",
    "ANNOUNCEMENTS_READ", "ANNOUNCEMENTS_MANAGE",
    "DOCUMENTS_READ", "DOCUMENTS_MANAGE",
    "LEADS_READ", "LEADS_MANAGE",
    "TRIALS_READ", "TRIALS_MANAGE",
    "AVAILABILITY_READ", "AVAILABILITY_MANAGE",
    "COMPENSATION_READ", "COMPENSATION_MANAGE",
    "PROGRESS_READ", "PROGRESS_MANAGE",
    "PROGRAMS_READ", "PROGRAMS_MANAGE",
    "COURSES_READ", "COURSES_MANAGE",
    "COHORTS_READ", "COHORTS_MANAGE",
    "CORPORATE_READ", "CORPORATE_MANAGE",
    "CERTIFICATES_READ", "CERTIFICATES_MANAGE",
    "COMPETENCIES_READ", "COMPETENCIES_MANAGE",
    "MATERIALS_READ", "MATERIALS_MANAGE",
    "TRAINING_ASSIGNMENTS_READ", "TRAINING_ASSIGNMENTS_MANAGE",
    "PROPOSALS_READ", "PROPOSALS_MANAGE",
    "COMMUNICATION_READ", "COMMUNICATION_MANAGE",
    "TEMPLATES_READ", "TEMPLATES_MANAGE",
    "CAMPAIGNS_READ", "CAMPAIGNS_MANAGE",
    "MESSAGES_READ", "MESSAGES_MANAGE",
    "CONTACT_REQUESTS_READ", "CONTACT_REQUESTS_MANAGE",
    "DELIVERY_LOGS_READ",
    "AI_ASSISTANT", "AI_INSIGHTS_READ", "AI_READ_FINANCE", "AI_READ_STUDENTS",
    "AI_READ_ATTENDANCE", "AI_READ_ACADEMIC", "AI_READ_CRM",
    "AI_KNOWLEDGE_MANAGE", "AI_RECOMMENDATIONS_READ",
    "BILLING_READ", "BILLING_INVOICES",
  ],
  TEACHER: [
    "STUDENTS_READ",
    "ATTENDANCE_READ", "ATTENDANCE_MANAGE",
    "REPORTS_READ",
    "SCHEDULES_READ",
    "GRADES_READ", "GRADES_MANAGE",
    "NOTIFICATIONS_READ",
    "AI_READ",
    "HOMEWORK_READ", "HOMEWORK_MANAGE",
    "REPORT_CARDS_READ",
    "ANNOUNCEMENTS_READ",
    "DOCUMENTS_READ",
    "PROGRESS_READ", "PROGRESS_MANAGE",
    "AVAILABILITY_READ",
    "COMMUNICATION_READ", "COMMUNICATION_MANAGE",
    "MESSAGES_READ", "MESSAGES_MANAGE",
    "CONTACT_REQUESTS_READ",
    "AI_ASSISTANT", "AI_INSIGHTS_READ", "AI_READ_ATTENDANCE", "AI_READ_ACADEMIC",
    "AI_RECOMMENDATIONS_READ",
  ],
  TRAINER: [
    "STUDENTS_READ",
    "ATTENDANCE_READ", "ATTENDANCE_MANAGE",
    "REPORTS_READ",
    "SCHEDULES_READ",
    "GRADES_READ", "GRADES_MANAGE",
    "NOTIFICATIONS_READ",
    "AI_READ",
    "HOMEWORK_READ", "HOMEWORK_MANAGE",
    "REPORT_CARDS_READ",
    "PROGRESS_READ", "PROGRESS_MANAGE",
    "PROGRAMS_READ",
    "COURSES_READ",
    "COHORTS_READ",
    "CERTIFICATES_READ",
    "COMPETENCIES_READ", "COMPETENCIES_MANAGE",
    "MATERIALS_READ", "MATERIALS_MANAGE",
    "TRAINING_ASSIGNMENTS_READ", "TRAINING_ASSIGNMENTS_MANAGE",
    "AVAILABILITY_READ",
    "COMMUNICATION_READ", "COMMUNICATION_MANAGE",
    "MESSAGES_READ", "MESSAGES_MANAGE",
    "CONTACT_REQUESTS_READ",
    "AI_ASSISTANT", "AI_INSIGHTS_READ", "AI_READ_ATTENDANCE", "AI_READ_ACADEMIC",
    "AI_RECOMMENDATIONS_READ",
  ],
  ACCOUNTANT: [
    "STUDENTS_READ",
    "FINANCE_READ", "FINANCE_MANAGE",
    "REPORTS_READ", "REPORTS_CREATE",
    "INVOICES_READ", "INVOICES_MANAGE",
    "PAYMENTS_READ", "PAYMENTS_MANAGE",
    "COMPENSATION_READ",
    "COMMUNICATION_READ",
    "MESSAGES_READ", "MESSAGES_MANAGE",
    "CONTACT_REQUESTS_READ",
    "AI_INSIGHTS_READ", "AI_READ_FINANCE",
    "BILLING_READ", "BILLING_INVOICES", "BILLING_PAYMENTS",
  ],
  RECEPTIONIST: [
    "STUDENTS_READ", "STUDENTS_CREATE", "STUDENTS_UPDATE",
    "TEACHERS_READ",
    "ORG_MEMBERS",
    "BRANCHES_READ",
    "ROOMS_READ",
    "SCHEDULES_READ",
    "GRADES_READ",
    "NOTIFICATIONS_READ",
    "ADMISSIONS_READ", "ADMISSIONS_MANAGE",
    "DOCUMENTS_READ", "DOCUMENTS_MANAGE",
    "LEADS_READ", "LEADS_MANAGE",
    "TRIALS_READ", "TRIALS_MANAGE",
    "PROGRAMS_READ",
    "COURSES_READ",
    "COHORTS_READ",
    "CORPORATE_READ",
    "CERTIFICATES_READ",
    "MATERIALS_READ",
    "TRAINING_ASSIGNMENTS_READ",
    "COMMUNICATION_READ", "COMMUNICATION_MANAGE",
    "MESSAGES_READ", "MESSAGES_MANAGE",
    "CONTACT_REQUESTS_READ", "CONTACT_REQUESTS_MANAGE",
    "DELIVERY_LOGS_READ",
    "AI_ASSISTANT", "AI_INSIGHTS_READ", "AI_READ_STUDENTS", "AI_READ_CRM",
  ],
  PARENT: [
    "STUDENTS_READ",
    "GRADES_READ",
    "NOTIFICATIONS_READ",
    "HOMEWORK_READ",
    "REPORT_CARDS_READ",
    "ANNOUNCEMENTS_READ",
    "DOCUMENTS_READ",
    "PROGRESS_READ",
    "MESSAGES_READ", "MESSAGES_MANAGE",
    "CONTACT_REQUESTS_READ", "CONTACT_REQUESTS_MANAGE",
    "AI_INSIGHTS_READ",
  ],
  STUDENT: [
    "STUDENTS_READ",
    "GRADES_READ",
    "NOTIFICATIONS_READ",
    "HOMEWORK_READ",
    "REPORT_CARDS_READ",
    "ANNOUNCEMENTS_READ",
    "PROGRESS_READ",
    "MESSAGES_READ", "MESSAGES_MANAGE",
    "CONTACT_REQUESTS_READ", "CONTACT_REQUESTS_MANAGE",
    "AI_INSIGHTS_READ",
  ],
};

// ─── Permission Checking ─────────────────────────────────────────

export type UserMembership = {
  organizationId: string;
  roleId: string;
  role: {
    name: string;
  };
};

export async function getUserPermissions(userId: string, organizationId: string): Promise<PermissionKey[]> {
  const membership = await db.organizationMember.findUnique({
    where: {
      organizationId_userId: { organizationId, userId },
    },
    include: {
      role: {
        include: {
          permissions: {
            include: { permission: true },
          },
        },
      },
    },
  });

  if (!membership || !membership.isActive) return [];

  return membership.role.permissions.map(
    (p) => p.permission.key as PermissionKey
  );
}

export async function hasPermission(
  userId: string,
  organizationId: string,
  permission: PermissionKey
): Promise<boolean> {
  const permissions = await getUserPermissions(userId, organizationId);
  return permissions.includes(permission);
}

export async function hasAnyPermission(
  userId: string,
  organizationId: string,
  perms: PermissionKey[]
): Promise<boolean> {
  const permissions = await getUserPermissions(userId, organizationId);
  return perms.some((p) => permissions.includes(p));
}

export async function requirePermission(
  userId: string,
  organizationId: string,
  permission: PermissionKey
): Promise<void> {
  const has = await hasPermission(userId, organizationId, permission);
  if (!has) {
    throw new Error(`Missing required permission: ${permission}`);
  }
}

// ─── Tenant Validation ───────────────────────────────────────────

export async function isOrganizationMember(
  userId: string,
  organizationId: string
): Promise<boolean> {
  const membership = await db.organizationMember.findUnique({
    where: {
      organizationId_userId: { organizationId, userId },
    },
  });
  return !!membership && membership.isActive;
}

export async function getUserOrganizations(userId: string) {
  return db.organizationMember.findMany({
    where: { userId, isActive: true },
    include: {
      organization: {
        select: {
          id: true,
          name: true,
          slug: true,
          type: true,
          isActive: true,
        },
      },
      role: {
        select: {
          id: true,
          name: true,
          displayName: true,
        },
      },
    },
  });
}
